# DATASET
TEST_DIR: /media/arvc/data/datasets/ARVCTRUSS/test/ply_xyzlabelnormal
FEATURES: [0,1,2,4,5,6]
LABELS: 3
NORMALIZE: True
BINARY: True
# THRESHOLD_METHOS POSIBILITIES = cuda:X, cpu
DEVICE: cpu
BATCH_SIZE: 1
# MODEL
MODEL_PATH: /home/arvc/PycharmProjects/arvc_PointNet/train_results/bin_seg_xyzxnynzn/pre-rec/230201_1200
#THRESHOLD: 0.25145065899674274
OUTPUT_CLASSES: 1
# LOSS = BCELoss()
# RESULTS
SAVE_PRED_CLOUDS: False
PRED_CLOUDS_DIR: /home/arvc/PycharmProjects/arvc_PointNet/pred_clouds_xyzxnynzn
